# Generated by Django 5.0.3 on 2024-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("ott_platforms", models.CharField(max_length=200)),
                ("imdb_rating", models.FloatField()),
                ("plot_description", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("poster_url", models.URLField()),
                ("watched", models.BooleanField(default=False)),
            ],
        ),
    ]
