# Generated by Django 5.0.3 on 2024-08-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=0),
        ),
    ]
