# Generated by Django 5.0.3 on 2024-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
