# Generated by Django 5.0.3 on 2024-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_movie_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
