# Generated by Django 5.0.3 on 2024-08-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_movie_movie_url_movie_trailer_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="ott_platforms",
            field=models.CharField(default="NONE", max_length=200),
        ),
    ]
