# Generated by Django 5.0.3 on 2024-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_remove_movie_duration_remove_movie_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="backdrop_path",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="overview",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="poster_path",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="runtime",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="vote_average",
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.CharField(default="0h 0m", max_length=20),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(default="NONE", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="plot_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
