# Generated by Django 5.0.3 on 2024-08-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_remove_movie_backdrop_path_remove_movie_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
