# Generated by Django 5.0.3 on 2024-08-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_alter_movie_tmdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
